#!/usr/bin/php
<?php

require __DIR__ . '/src/CLI.php';

class Tribe_Product_Util_CLI_ReleaseDate extends \TUT\CLI {
	/**
	 * Friendly plugin name
	 */
	public $friendly_script_name = 'Plugin release date setter';

	public function __construct() {
		parent::__construct();

		$this->process();
	}

	public function process() {
		$version      = $this->version_prompt( 'What version are you preparing?' );
		$release_date = $this->prompt( 'What is the date of the release?' );
		$branch       = $this->prompt_and_confirm(
			'In which branch would you like to change the version date?',
			'Are you sure you wish to change the version date in the %s branch?'
		);

		foreach ( $this->selected_plugins as $plugin ) {
			echo "-------------------\n";
			echo "{$plugin}\n";

			$plugin_dir = "{$this->origin_dir}/{$plugin}";

			if ( ! file_exists( $plugin_dir ) ) {
				echo "The {$plugin} directory doesn't exist here!\n";
				exit;
			}

			// cd into the plugin directory
			chdir( $plugin_dir );

			// checkout branch
			echo shell_exec( "git checkout {$branch}" );

			if ( ! file_exists( 'readme.txt' ) ) {
				echo "There isn't a readme.txt file that can be edited!\n";
				exit;
			}

			$readme = file_get_contents( 'readme.txt' );
			$regex_version = preg_quote( $version );
			$readme = preg_replace(
				'/= \[' . $regex_version . '\] [^\=]*\=/',
				"= [{$version}] {$release_date} =",
				$readme
			);
			file_put_contents( 'readme.txt', $readme );

			$this->commit_prompt();

			// go back a directory
			chdir( '../' );
		}//end foreach

		echo "-------------------\n";
		echo "DONE\n";
	}
}

new Tribe_Product_Util_CLI_ReleaseDate;
