#!/usr/bin/php
<?php

require __DIR__ . '/src/CLI.php';

class Tribe_Product_Util_CLI_Views extends \TUT\CLI {
	/**
	 * Friendly plugin name
	 */
	public $friendly_script_name = 'Finds changed views';

	/**
	 * Branch to update
	 */
	public $branch;

	public function __construct() {
		$this->supported_args['short'] = 'b::';
		$this->supported_args['long'] = [
			'branch::',
		];

		parent::__construct();

		$this->process();
	}

	public function parse_args() {
		global $argv;

		if ( ! empty( $this->args['b'] ) ) {
			$this->branch = $this->args['b'];
		} elseif ( ! empty( $this->args['branch'] ) ) {
			$this->branch = $this->args['branch'];
		} elseif ( ! empty( $argv ) ) {
			$this->branch = $argv[1];
		}

		if ( empty( $this->branch ) ) {
			echo "You must specify the branch you wish to switch plugins to\n";
			exit;
		}
	}

	public function process() {
		if ( 'mr' === $this->branch ) {
			$doc = file_get_contents( 'http://inside.tri.be/maintenance-releases/?heckyeah=howweroll' );
		}

		$view_report = '';

		$changed_views = array();

		foreach ( $this->selected_plugins as $plugin ) {
			echo "-------------------\n";

			$plugin_dir = "{$this->origin_dir}/{$plugin}";

			if ( file_exists( $plugin_dir ) ) {
				echo "{$plugin}\n";

				// cd into the plugin directory
				chdir( $plugin_dir );

				if ( 'mr' === $this->branch ) {
					preg_match( '!"https://github.com/moderntribe/' . preg_quote( $plugin ) . '/tree/release/([^"]+)"!', $doc, $matches );
					$branch = "release/{$matches[1]}";
				} else {
					$branch = $this->branch;
				}

				$this->sync_branch( $branch );

				$changed_views[ $plugin ] = $this->changed_views( $plugin );

				// go back up to the plugins directory
				chdir( '../' );
			} else {
				echo "{$plugin} doesn't exist in this directory. Perhaps you aren't in executing this from plugins?\n";
			}
		}

		echo "-------------------\n";
		echo "Changed views:\n";
		foreach ( $changed_views as $plugin => $data ) {
			if ( ! $data ) {
				continue;
			}

			echo "\n**{$plugin}**\n";
			echo "==========================\n";
			foreach ( (array) $data as $file => $info ) {
				echo "* {$file}";
				if ( ! $info['view-version'] ) {
					echo ' - NO @version SET';
				} elseif ( $info['view-version'] !== $info['bootstrap-version'] ) {
					echo " - @version MISMATCH: Plugin version: {$info['bootstrap-version']} vs. View version: {$info['view-version']}";
				}
				echo "\n";
			}
		}
		echo $view_report;
		echo "\n\n";
	}
}

new Tribe_Product_Util_CLI_Views;
