#!/usr/bin/env php
<?php

require dirname( __FILE__ ) . '/vendor/autoload.php';

define( '__TUT_DIR__', __DIR__ );
define( 'TUT_VERSION', '1.2.9' );

use Symfony\Component\Console\Application;
use TUT\Commands;

$dotenv = \Dotenv\Dotenv::createImmutable( __DIR__ );
$dotenv->load();

$application = new Application();

$art = <<<ART
                              /^\
           L L               /   \               L L
        __/|/|_             /  .  \             _|\|\__
       /_| [_[_\           /     .-\           /_]_] |_\
      /__\  __`-\_____    /    .    \    _____/-`__  /__\
     /___] /=@>  _   {>  /-.         \  <}   _  <@=\ [___\
    /____/     /` `--/  /      .      \  \--` `\     \____\
   /____/  \____/`-._> /               \ <_.-`\____/  \____\
  /____/    /__/      /-._     .   _.-  \      \__\    \____\
 /____/    /__/      /         .         \      \__\    \____\
|____/_  _/__/      /          .          \      \__\_  _\____|
 \__/_ ``_|_/      /      -._  .        _.-\      \_|_`` _\___/
   /__`-`__\      <_         `-;           _>      /__`-`__\
      `-`           `-._       ;       _.-`           `-`
                        `-._   ;   _.-`
                            `-._.-`
ART;

$application->setName( "{$art}\n\nThe Events Calendar Utilities (tut)" );

$application->add( new Commands\Analyze );
$application->add( new Commands\BranchList );
$application->add( new Commands\Build );
$application->add( new Commands\ChangedViews );
$application->add( new Commands\Extension\Create );
$application->add( new Commands\Extension\SetDependency );
$application->add( new Commands\GenerateCSSOverride );
$application->add( new Commands\GetBuildNumber );
$application->add( new Commands\GetHash );
$application->add( new Commands\GetZipFilename );
$application->add( new Commands\Git\File );
$application->add( new Commands\Git\GitClone );
$application->add( new Commands\I18n\GlotPress );
$application->add( new Commands\ListTemplates );
$application->add( new Commands\Package );
$application->add( new Commands\ReleaseDate );
$application->add( new Commands\Reset );
$application->add( new Commands\SubmoduleSync );
$application->add( new Commands\Sync );
$application->add( new Commands\TBD );
$application->add( new Commands\Version );
$application->add( new Commands\Upgrade );
$application->add( new Commands\SvnTag );

$application->run();
